### ISSUE TITLE
Ist PyRMVtransport ein Modul von/für den home-assistant mehr?

### ISSUE THREAD

**Issue by ohobby** [cgtobi/PyRMVtransport#1]
Hi,

ist  PyRMVtransport ein Modul von/für  den home-assistant oder auch alleine Nutzbar?

Bin über das Teil gestolpert, weil ich eine Lösung zur Abfrage der RMV API gesucht habe um mir für meine Stationen die nächsten Abfahrtzeiten anzeigen zu lassen.

Grüße,
Oliver

**Comment by cgtobi** [comment]
Hi Oliver,

klar kannst du das auch alleine nutzbar. Ich werde in den nächsten Tagen ein wenig Dokumentation erstellen. 

Hier schon mal ein Beispielaufruf:

```python
import RMVtransport

rmv = RMVtransport.RMVtransport()

# Abfahrten für Station 3006904 Mainz Hauptbahnhof
rmv.get_departures(stationId='3006904')
rmv.output()

# Abfahrten als JSON für Station 3006907 Wiesbaden Hauptbahnhof
# maximal 5 Ergebnisse
# nur S-Bahn, U-Bahn und Tram
print(rmv.get_departures(stationId='3006907', products=['S', 'U-Bahn', 'Tram'], maxJourneys=5))
```

Gruß,
Tobias

**Comment by ohobby** [comment]
Hallo Tobias,

werde mir den home-assistant  aber mal ansehen, da ich auch die rmv-card interessant finde und der assistant interessant ist. 

Danke für die schnelle Antwort.

Grüße,
Oliver
